# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Allcomp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_List(object):
    def setupUi(self, List):
        List.setObjectName("List")
        List.resize(455, 600)
        self.centralwidget = QtWidgets.QWidget(List)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(25, 10, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(25, 50, 400, 531))
        self.textBrowser.setObjectName("textBrowser")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(285, 5, 140, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Back.setFont(font)
        self.Back.setObjectName("Back")
        List.setCentralWidget(self.centralwidget)

        self.retranslateUi(List)
        QtCore.QMetaObject.connectSlotsByName(List)

    def retranslateUi(self, List):
        _translate = QtCore.QCoreApplication.translate
        List.setWindowTitle(_translate("List", "MainWindow"))
        self.label_2.setText(_translate("List", "СПИСОК КОМПАНИЙ"))
        self.Back.setText(_translate("List", "Назад"))
