# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/favorites.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Favorites(object):
    def setupUi(self, Favorites):
        Favorites.setObjectName("Favorites")
        Favorites.resize(358, 250)
        self.centralwidget = QtWidgets.QWidget(Favorites)
        self.centralwidget.setObjectName("centralwidget")
        self.Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Delete.setGeometry(QtCore.QRect(190, 10, 140, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Delete.setFont(font)
        self.Delete.setObjectName("Delete")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(30, 10, 140, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Add.setFont(font)
        self.Add.setObjectName("Add")
        self.Favlist = QtWidgets.QTextBrowser(self.centralwidget)
        self.Favlist.setGeometry(QtCore.QRect(30, 50, 300, 192))
        self.Favlist.setObjectName("Favlist")
        Favorites.setCentralWidget(self.centralwidget)

        self.retranslateUi(Favorites)
        QtCore.QMetaObject.connectSlotsByName(Favorites)

    def retranslateUi(self, Favorites):
        _translate = QtCore.QCoreApplication.translate
        Favorites.setWindowTitle(_translate("Favorites", "Favorites"))
        self.Delete.setText(_translate("Favorites", "Удалить"))
        self.Add.setText(_translate("Favorites", "Добавить"))
