# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Istok_relevants.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Istok_relevants(object):
    def setupUi(self, Istok_relevants):
        Istok_relevants.setObjectName("Istok_relevants")
        Istok_relevants.resize(455, 250)
        font = QtGui.QFont()
        font.setPointSize(6)
        Istok_relevants.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Istok_relevants)
        self.centralwidget.setObjectName("centralwidget")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(410, 10, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.right.setFont(font)
        self.right.setObjectName("right")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(370, 10, 31, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.left.setFont(font)
        self.left.setObjectName("left")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(310, 10, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 70, 175, 175))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(260, 70, 175, 175))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(20, 40, 175, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(260, 40, 175, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setObjectName("textBrowser_5")
        Istok_relevants.setCentralWidget(self.centralwidget)

        self.retranslateUi(Istok_relevants)
        QtCore.QMetaObject.connectSlotsByName(Istok_relevants)

    def retranslateUi(self, Istok_relevants):
        _translate = QtCore.QCoreApplication.translate
        Istok_relevants.setWindowTitle(_translate("Istok_relevants", "Istok_relevants"))
        self.right.setText(_translate("Istok_relevants", ">"))
        self.left.setText(_translate("Istok_relevants", "<"))
        self.label.setText(_translate("Istok_relevants", "PAGE"))
