# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/MainIstok.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Istok(object):
    def setupUi(self, Istok):
        Istok.setObjectName("Istok")
        Istok.resize(455, 150)
        self.centralwidget = QtWidgets.QWidget(Istok)
        self.centralwidget.setObjectName("centralwidget")
        self.Allcomp = QtWidgets.QPushButton(self.centralwidget)
        self.Allcomp.setGeometry(QtCore.QRect(0, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Allcomp.setFont(font)
        self.Allcomp.setObjectName("Allcomp")
        self.Relevcomp = QtWidgets.QPushButton(self.centralwidget)
        self.Relevcomp.setGeometry(QtCore.QRect(0, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Relevcomp.setFont(font)
        self.Relevcomp.setObjectName("Relevcomp")
        self.Status = QtWidgets.QTextBrowser(self.centralwidget)
        self.Status.setGeometry(QtCore.QRect(230, 110, 221, 31))
        self.Status.setObjectName("Status")
        self.Detail = QtWidgets.QPushButton(self.centralwidget)
        self.Detail.setGeometry(QtCore.QRect(230, 10, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Detail.setFont(font)
        self.Detail.setObjectName("Detail")
        Istok.setCentralWidget(self.centralwidget)

        self.retranslateUi(Istok)
        QtCore.QMetaObject.connectSlotsByName(Istok)

    def retranslateUi(self, Istok):
        _translate = QtCore.QCoreApplication.translate
        Istok.setWindowTitle(_translate("Istok", "Istok"))
        self.Allcomp.setText(_translate("Istok", "Вывод всех компаний"))
        self.Relevcomp.setText(_translate("Istok", "Наиболее релевантные"))
        self.Detail.setText(_translate("Istok", "Детальное \n"
"отслеживание"))
