# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/MainIstok.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Istok(object):
    def setupUi(self, Istok):
        Istok.setObjectName("Istok")
        Istok.resize(455, 150)
        self.centralwidget = QtWidgets.QWidget(Istok)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 110, 221, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 10, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        Istok.setCentralWidget(self.centralwidget)

        self.retranslateUi(Istok)
        QtCore.QMetaObject.connectSlotsByName(Istok)

    def retranslateUi(self, Istok):
        _translate = QtCore.QCoreApplication.translate
        Istok.setWindowTitle(_translate("Istok", "Istok"))
        self.pushButton.setText(_translate("Istok", "Вывод всех компаний"))
        self.pushButton_2.setText(_translate("Istok", "Наиболее релевантные"))
        self.pushButton_3.setText(_translate("Istok", "Детальное \n"
"отслеживание"))
