# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Search(object):
    def setupUi(self, Search):
        Search.setObjectName("Search")
        Search.resize(358, 249)
        self.centralwidget = QtWidgets.QWidget(Search)
        self.centralwidget.setObjectName("centralwidget")
        self.Searchline = QtWidgets.QLineEdit(self.centralwidget)
        self.Searchline.setGeometry(QtCore.QRect(30, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Searchline.setFont(font)
        self.Searchline.setText("")
        self.Searchline.setObjectName("Searchline")
        self.Go = QtWidgets.QPushButton(self.centralwidget)
        self.Go.setGeometry(QtCore.QRect(270, 10, 62, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Go.setFont(font)
        self.Go.setObjectName("Go")
        self.Result = QtWidgets.QTextBrowser(self.centralwidget)
        self.Result.setGeometry(QtCore.QRect(30, 50, 300, 160))
        self.Result.setObjectName("Result")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(30, 215, 140, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Back.setFont(font)
        self.Back.setObjectName("Back")
        self.Choose = QtWidgets.QPushButton(self.centralwidget)
        self.Choose.setGeometry(QtCore.QRect(190, 215, 140, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Choose.setFont(font)
        self.Choose.setObjectName("Choose")
        Search.setCentralWidget(self.centralwidget)

        self.retranslateUi(Search)
        QtCore.QMetaObject.connectSlotsByName(Search)

    def retranslateUi(self, Search):
        _translate = QtCore.QCoreApplication.translate
        Search.setWindowTitle(_translate("Search", "Search"))
        self.Searchline.setPlaceholderText(_translate("Search", "Поиск"))
        self.Go.setText(_translate("Search", "GO"))
        self.Back.setText(_translate("Search", "Назад"))
        self.Choose.setText(_translate("Search", "Выбрать"))
